### ISSUE TITLE
Sonoff M5 configs

### ISSUE THREAD

**Issue by egrinaldi** [velijv/esphome-configs#1]
Hi, I'm trying to get the sonoff M5 configs but can't find them. Please let me know if you have them or where can I get the config files for the switches. Thank you!

**Comment by velijv** [comment]
Added configs for all Switchman M5 models. 

I have all listed ones done and in personal use, but haven't had time yet to sanitize the yaml and edit them to the project-template format for public adoption. 👨🏿‍💻

**Comment by egrinaldi** [comment]
Thanks! Great work!
